name: Deploy static wasm

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.36.0'

      - name: Build WASM binary
        run: |
          tinygo build -o ./static/main.wasm -target wasm --no-debug --panic trap ./games/all
          cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js ./static/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
